name: "🚀 Feature Request"
description: Suggest an idea for this project
title: "[REQUEST]: "
labels: [enhancement]
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        Please keep in mind that OpenBullet is a [free and open-source](https://github.com/openbullet/OpenBullet2) project, made up entirely and exclusively of **volunteers** who donate their free time to the project.
  - type: checkboxes
    id: before-posting
    attributes:
      label: "This feature request respects the following points:"
      description: All conditions are **required**. Failure to comply with any of these conditions may cause your feature request to be closed without comment.
      options:
        - label: This is a **feature request**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
          required: true
        - label: This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) _(I've searched it)_.
          required: true
        - label: I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
          required: true
        - label: I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
          required: true
        - label: This report addresses only a single feature request; If you have multiple feature request, kindly create separate reports for each one.
          required: true
  - type: markdown
    id: preliminary-information
    attributes:
      value: |
        ### General preliminary information

        Please keep the following in mind when creating this issue:

        1. Fill in as much of the template as possible.
        2. Provide as much detail as possible. Do not assume other people to know what is going on.
        3. Keep everything readable and structured. Nobody enjoys reading poorly written reports that are difficult to understand.
        4. Keep an eye on your report as long as it is open, your involvement might be requested at a later moment.
        5. Keep the title short and descriptive. The title is not the place to write down a full description of the issue.
        6. When deciding to leave out information in a field, leave it blank and empty. Avoid writing things such as `n/a` for empty fields.
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the feature request
      description: Please provide a detailed description of the feature request, in a readable and comprehensible way.
      placeholder: |
        I would like to see a new feature that allows users to [...] 
  - type: textarea
    id: related-problems
    attributes:
        label: Is your feature request related to a problem
        description: A clear and concise description of what the problem is.     
        placeholder: |
            I'm always frustrated when [...]
  - type: textarea
    id: solution-description
    attributes:
        label: Describe the solution you'd like
        description: A clear and concise description of what you want to happen.     
        placeholder: |
            I would like to see [...]
  - type: textarea
    id: alternative-description
    attributes:
        label: Describe alternatives you've considered
        description: A clear and concise description of any alternative solutions or features you've considered.   
        placeholder: |
            I've considered [...]
  - type: textarea
    id: screenshots
    attributes:
      label: Relevant screenshots or videos
      description: Attach relevant screenshots or videos related to this report.
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any additional information that might be useful to this feature request.
